/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingProgramsRouteImport } from './routes/upcoming-programs'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DonationPolicyRouteImport } from './routes/donation-policy'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const UpcomingProgramsRoute = UpcomingProgramsRouteImport.update({
  id: '/upcoming-programs',
  path: '/upcoming-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationPolicyRoute = DonationPolicyRouteImport.update({
  id: '/donation-policy',
  path: '/donation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/donate': typeof DonateRoute
  '/donation-policy': typeof DonationPolicyRoute
  '/gallery': typeof GalleryRoute
  '/leadership': typeof LeadershipRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/upcoming-programs': typeof UpcomingProgramsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/donate': typeof DonateRoute
  '/donation-policy': typeof DonationPolicyRoute
  '/gallery': typeof GalleryRoute
  '/leadership': typeof LeadershipRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/upcoming-programs': typeof UpcomingProgramsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/donate': typeof DonateRoute
  '/donation-policy': typeof DonationPolicyRoute
  '/gallery': typeof GalleryRoute
  '/leadership': typeof LeadershipRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/upcoming-programs': typeof UpcomingProgramsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/donate'
    | '/donation-policy'
    | '/gallery'
    | '/leadership'
    | '/privacy'
    | '/terms'
    | '/upcoming-programs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/donate'
    | '/donation-policy'
    | '/gallery'
    | '/leadership'
    | '/privacy'
    | '/terms'
    | '/upcoming-programs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/donate'
    | '/donation-policy'
    | '/gallery'
    | '/leadership'
    | '/privacy'
    | '/terms'
    | '/upcoming-programs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DonateRoute: typeof DonateRoute
  DonationPolicyRoute: typeof DonationPolicyRoute
  GalleryRoute: typeof GalleryRoute
  LeadershipRoute: typeof LeadershipRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  UpcomingProgramsRoute: typeof UpcomingProgramsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming-programs': {
      id: '/upcoming-programs'
      path: '/upcoming-programs'
      fullPath: '/upcoming-programs'
      preLoaderRoute: typeof UpcomingProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donation-policy': {
      id: '/donation-policy'
      path: '/donation-policy'
      fullPath: '/donation-policy'
      preLoaderRoute: typeof DonationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DonateRoute: DonateRoute,
  DonationPolicyRoute: DonationPolicyRoute,
  GalleryRoute: GalleryRoute,
  LeadershipRoute: LeadershipRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  UpcomingProgramsRoute: UpcomingProgramsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
